### ISSUE TITLE
Why don't wrap the code into a CustomView?

### ISSUE THREAD

**Issue by ryanhoo** [jivesoftware/PDTSimpleCalendar#53]
As we can see, there is only a ViewController. Obviously it is not convenient for reuse in multiple View Controllers.

**Comment by jmig** [comment]
ViewController containment is available since iOS5 and works fairly well now ;-)

I agree that we could use a better separation View / ViewController & that delegate / data source could (should??) be different objects.
We also have UIScrollViewDelegate methods that we implement, a convenient way to have all this together was to use a ViewController.

If I was designing this component today, I'll probably do it differently and probably toward what you suggest.

If you're willing to do it, please do. We can even have a backward compatibility mode by implementing a really stupid PDTSimpleCalendarViewController that would just load the proper view.
