### ISSUE TITLE
didSelectDate returns one day less

### ISSUE THREAD

**Issue by IcuScc** [jivesoftware/PDTSimpleCalendar#57]
Hi. 
when i select a date from calendar, didSelectDate method returns on day less. For example, if a i select 18-03-2105, didSelectDate returns 17-03-2015

Why?

Thankyou

**Comment by vishw3** [comment]
same issue here .... did u fix it

**Comment by jmig** [comment]
Can you tell me on which timezone you are?

**Comment by jmig** [comment]
Ok it was easy to reproduce with a  default timezone set to GMT +x.

I set my Computer's timezone to GMT+1 (Berlin Time) to be precise.
The simulator takes the computer's timezone as its default timezone.

When selecting a date in the calendar I can see in the log :
`2015-03-16 16:31:38.367 PDTSimpleCalendarDemo[2833:386643] Date Selected : 2015-03-16 23:00:00 +0000`
Even though I clicked on March 17 cell.

That's because the NSDate object is using GMT as its timezone (note the +0000 at the end) & the calendar returns the date selected at 0:00 am.

So when it's March 17, 0:00am in Berlin, it's March 16, 11pm (or 23:00) in GMT. Hence why you see "one day less" when selecting the date.

I strongly encourage you to do your date calculation/storage using GMT, and then display the dates in the user local format. iOS makes it really really easy for us.
You should look at `[NSLocale currentLocale]` & `NSDateFormatter`.

A quick example to show that it works:
Assuming my default timezone is GMT + 1 (Berlin)

````
#pragma mark - PDTSimpleCalendarViewDelegate

- (void)simpleCalendarViewController:(PDTSimpleCalendarViewController *)controller didSelectDate:(NSDate *)date
{
    NSLog(@"Date Selected : %@",date);
    NSLog(@"Date Selected with Locale %@", [date descriptionWithLocale:[NSLocale systemLocale]]);
}
````
will display : 

````
2015-03-16 16:38:07.896 PDTSimpleCalendarDemo[3061:403624] Date Selected : 2015-03-16 23:00:00 +0000
2015-03-16 16:38:07.897 PDTSimpleCalendarDemo[3061:403624] Date Selected with Locale 2015 M03 17, Tue 00:00:00 GMT+01:00
````

I hope this helps!
I will add a comment in the delegate method to indicate that the selectedDate returned is using GMT.

**Comment by vishw3** [comment]
thanks this works...
